# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    my_user_provider.class: AppBundle\Security\Core\User\FOSUBUserProvider

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    twig.extension.intl:
            class: Twig_Extensions_Extension_Intl
            tags:
                - { name: twig.extension }
    my_user_provider:
            class: "%my_user_provider.class%"
            #this is the place where the properties are passed to the UserProvider - see config.yml
            arguments:
              - '@fos_user.user_manager'
              - {facebook: facebook_id}
    app.form.registration:
            class: AppBundle\Form\RegistrationType
            tags:
                - { name: form.type, alias: app_user_registration }
    twig.extension.sortbyfield:
            class: Snilius\Twig\SortByFieldExtension
            tags:
                - { name: twig.extension }
    app.security.authentication_handler:
            class: AppBundle\Security\Core\AuthenticationHandler
            public: false
            arguments:
                - '@router'
                - '@session'
    dpolac.twig_lambda.extension:
            class: DPolac\TwigLambda\LambdaExtension
            tags: [ { name: twig.extension } ]
    #email_manager:
    #    class: Swift_Mailer
    #    arguments:
    #      - '@mailer'
    #    scope: request